# OpenAI API - Questions

© Advanced Analytics, Amir Ben Haim, 2024

<br></br>
<br></br>
## Exercise 1

### First, get an "api key"

In order to use the OpenAI language model, users are required to generate a token.
<br></br>
<u>Follow these simple steps to generate a token with openai:</u>
- Go to <a href="url">https://platform.openai.com/apps</a>  and signup with your email address or connect your Google Account.
- Go to View API Keys on left side of your Personal Account Settings
- Select Create new Secret key
- The API access to OPENAI is a paid service
- You have to set up billing
- You don’t need ChatGPT Plus - The API and ChatGPT subscriptions are billed separately
<br></br>
<p style="background-color:Tomato"> Make sure you read the Pricing information before experimenting</p>
<p style="background-color:Tomato">Once you add your API key, make sure to not share it with anyone! The API key should remain private</p>
<p style="background-color:Tomato">Use the <code>.env</code> file for you API key</p>

<br></br>
<br></br>
## Exercise 2

### Import `NORTHWND_prd.csv` into a `df`

- Keep only products with
    ```python
    df.CategoryID == 1
    ```
- Keep only columns:
    ```python
    ['ProductID', 'ProductName', 'CategoryID','QuantityPerUnit', 'UnitPrice', 'UnitsInStock']
    ```

<br>

In [3]:
from dotenv import load_dotenv
import os
from openai import OpenAI
import pandas as pd

load_dotenv()  # Load variables from .env file
api_key = os.getenv("OPENAI_API_KEY")

# Create an OpenAI client instance
client = OpenAI(api_key=api_key)

In [39]:
df = pd.read_csv("NORTHWND_prd.csv", encoding="cp1252")
df = df.loc[df.CategoryID == 1, ['ProductID', 'ProductName', 'CategoryID','QuantityPerUnit', 'UnitPrice', 'UnitsInStock']]
df

,ProductID,ProductName,CategoryID,QuantityPerUnit,UnitPrice,UnitsInStock
0,1,Chai,1,10 boxes x 20 bags,18.00,39
1,2,Chang,1,24 - 12 oz bottles,19.00,17
23,24,Guaraná Fantástica,1,12 - 355 ml cans,4.50,20
33,34,Sasquatch Ale,1,24 - 12 oz bottles,14.00,111
34,35,Steeleye Stout,1,24 - 12 oz bottles,18.00,20
37,38,Côte de Blaye,1,12 - 75 cl bottles,263.50,17
38,39,Chartreuse verte,1,750 cc per bottle,18.00,69
42,43,Ipoh Coffee,1,16 - 500 g tins,46.00,17
66,67,Laughing Lumberjack Lager,1,24 - 12 oz bottles,14.00,52
69,70,Outback Lager,1,24 - 355 ml bottles,15.00,15
74,75,Rhönbräu Klosterbier,1,24 - 0.5 l bottles,7.75,125
75,76,Lakkalikööri,1,500 ml,18.00,57

<br></br>
<br></br>
## Exercise 3

### Use OpenAI API to add a new COLUMN for `df`

- Name the column `ProductSize`
- Categorize each product to be `Big` or `Small` base on the `QuantityPerUnit` column
<br></br>

- For each API call only ONE product `QuantityPerUnit` should be passed
    <p style="font-size:20px;color:Tomato"> USE a `for loop` to do so </p>

In [56]:
df = pd.read_csv("NORTHWND_prd.csv", encoding="cp1252")
df = df.loc[df.CategoryID == 1, ['ProductID', 'ProductName', 'CategoryID','QuantityPerUnit', 'UnitPrice', 'UnitsInStock']]
df["ProductSize"]= None

context_prompt = "You are a skillful analyst that decides if Product is big or small based on the QuantityPerUnit column that you receive, analyze if that quantity per unit makes it Big or Small and you answer your result in a single word Big or Small."
for i in df.index:
  
  instructions_prompt = f"""
  Given the following QuantityPerUnit: {df.loc[i, "QuantityPerUnit"]}, make your analysis and decide if the Product is big or small and answer in a single word Big or Small.:
  
  """
  print(df.loc[i, "QuantityPerUnit"])
  completion = client.chat.completions.create(
    model="gpt-4o",
    messages=[
      {"role": "system", "content":context_prompt},
      {"role": "user", "content": instructions_prompt}
    ]
  )

  df.loc[i, "ProductSize"] = completion.choices[0].message.content
  print(df.loc[i, "ProductSize"])
df

10 boxes x 20 bags
Big
24 - 12 oz bottles
Small
12 - 355 ml cans
Small
24 - 12 oz bottles
Small
24 - 12 oz bottles
Small
12 - 75 cl bottles
Small
750 cc per bottle
Small
16 - 500 g tins
Small
24 - 12 oz bottles
Small
24 - 355 ml bottles
Small
24 - 0.5 l bottles
Small
500 ml
Small

,ProductID,ProductName,CategoryID,QuantityPerUnit,UnitPrice,UnitsInStock,ProductSize
0,1,Chai,1,10 boxes x 20 bags,18.00,39,Big
1,2,Chang,1,24 - 12 oz bottles,19.00,17,Small
23,24,Guaraná Fantástica,1,12 - 355 ml cans,4.50,20,Small
33,34,Sasquatch Ale,1,24 - 12 oz bottles,14.00,111,Small
34,35,Steeleye Stout,1,24 - 12 oz bottles,18.00,20,Small
37,38,Côte de Blaye,1,12 - 75 cl bottles,263.50,17,Small
38,39,Chartreuse verte,1,750 cc per bottle,18.00,69,Small
42,43,Ipoh Coffee,1,16 - 500 g tins,46.00,17,Small
66,67,Laughing Lumberjack Lager,1,24 - 12 oz bottles,14.00,52,Small
69,70,Outback Lager,1,24 - 355 ml bottles,15.00,15,Small
74,75,Rhönbräu Klosterbier,1,24 - 0.5 l bottles,7.75,125,Small
75,76,Lakkalikööri,1,500 ml,18.00,57,Small

,ProductID,ProductName,CategoryID,QuantityPerUnit,UnitPrice,UnitsInStock,ProductSize
0,1,Chai,1,10 boxes x 20 bags,18.00,39,Big
1,2,Chang,1,24 - 12 oz bottles,19.00,17,Small
23,24,Guaraná Fantástica,1,12 - 355 ml cans,4.50,20,Small
33,34,Sasquatch Ale,1,24 - 12 oz bottles,14.00,111,Big
34,35,Steeleye Stout,1,24 - 12 oz bottles,18.00,20,Big
37,38,Côte de Blaye,1,12 - 75 cl bottles,263.50,17,Small
38,39,Chartreuse verte,1,750 cc per bottle,18.00,69,Small
42,43,Ipoh Coffee,1,16 - 500 g tins,46.00,17,Big
66,67,Laughing Lumberjack Lager,1,24 - 12 oz bottles,14.00,52,Big
69,70,Outback Lager,1,24 - 355 ml bottles,15.00,15,Big
74,75,Rhönbräu Klosterbier,1,24 - 0.5 l bottles,7.75,125,Big
75,76,Lakkalikööri,1,500 ml,18.00,57,Small

Let's Check how many big or small products we have

<br></br>
<br></br>
## Exercise 4

<br></br>
#### Let's Check if fine-tuning the parameters model will change the result

Add:

```python
    max_tokens=5,  # Since we expect only one word, we keep max_tokens low
    temperature=0.0  # Setting temperature to 0 for deterministic results

```

In [57]:
df = pd.read_csv("NORTHWND_prd.csv", encoding="cp1252")
df = df.loc[df.CategoryID == 1, ['ProductID', 'ProductName', 'CategoryID','QuantityPerUnit', 'UnitPrice', 'UnitsInStock']]
df["ProductSize"]= None

context_prompt = "You are a skillful analyst that decides if Product is big or small based on the QuantityPerUnit column that you receive, analyze if that quantity per unit makes it Big or Small and you answer your result in a single word Big or Small."
for i in df.index:
  
  instructions_prompt = f"""
  Given the following QuantityPerUnit: {df.loc[i, "QuantityPerUnit"]}, make your analysis and decide if the Product is big or small and answer in a single word Big or Small.:
  
  """
  print(df.loc[i, "QuantityPerUnit"])
  completion = client.chat.completions.create(
    model="gpt-4o",
    messages=[
      {"role": "system", "content":context_prompt},
      {"role": "user", "content": instructions_prompt}
    ],
    temperature=0.0,
    max_tokens=5
  )

  df.loc[i, "ProductSize"] = completion.choices[0].message.content
  print(df.loc[i, "ProductSize"])
df

10 boxes x 20 bags
Big
24 - 12 oz bottles
Small
12 - 355 ml cans
Small
24 - 12 oz bottles
Small
24 - 12 oz bottles
Small
12 - 75 cl bottles
Small
750 cc per bottle
Small
16 - 500 g tins
Small
24 - 12 oz bottles
Small
24 - 355 ml bottles
Small
24 - 0.5 l bottles
Small
500 ml
Small

,ProductID,ProductName,CategoryID,QuantityPerUnit,UnitPrice,UnitsInStock,ProductSize
0,1,Chai,1,10 boxes x 20 bags,18.00,39,Big
1,2,Chang,1,24 - 12 oz bottles,19.00,17,Small
23,24,Guaraná Fantástica,1,12 - 355 ml cans,4.50,20,Small
33,34,Sasquatch Ale,1,24 - 12 oz bottles,14.00,111,Small
34,35,Steeleye Stout,1,24 - 12 oz bottles,18.00,20,Small
37,38,Côte de Blaye,1,12 - 75 cl bottles,263.50,17,Small
38,39,Chartreuse verte,1,750 cc per bottle,18.00,69,Small
42,43,Ipoh Coffee,1,16 - 500 g tins,46.00,17,Small
66,67,Laughing Lumberjack Lager,1,24 - 12 oz bottles,14.00,52,Small
69,70,Outback Lager,1,24 - 355 ml bottles,15.00,15,Small
74,75,Rhönbräu Klosterbier,1,24 - 0.5 l bottles,7.75,125,Small
75,76,Lakkalikööri,1,500 ml,18.00,57,Small

<br></br>
<br></br>
## Exercise 5

<br></br>
#### Let's add Context:

```python
context_prompt = "You're helping me to categorize each product by its 'QuantityPerUnit' description , the categories are 'Big' or 'Small'"
```

In [58]:
df = pd.read_csv("NORTHWND_prd.csv", encoding="cp1252")
df = df.loc[df.CategoryID == 1, ['ProductID', 'ProductName', 'CategoryID','QuantityPerUnit', 'UnitPrice', 'UnitsInStock']]
df["ProductSize"]= None

context_prompt = "You're helping me to categorize each product by its 'QuantityPerUnit' description , the categories are 'Big' or 'Small'."
for i in df.index:
  
  instructions_prompt = f"""
  Given the following QuantityPerUnit: {df.loc[i, "QuantityPerUnit"]}, make your analysis and decide if the Product is big or small and answer in a single word Big or Small.:
  
  """
  print(df.loc[i, "QuantityPerUnit"])
  completion = client.chat.completions.create(
    model="gpt-4o",
    messages=[
      {"role": "system", "content":context_prompt},
      {"role": "user", "content": instructions_prompt}
    ],
    temperature=0.0,
    max_tokens=5
  )

  df.loc[i, "ProductSize"] = completion.choices[0].message.content
  print(df.loc[i, "ProductSize"])
df

10 boxes x 20 bags
Big
24 - 12 oz bottles
Big
12 - 355 ml cans
Small
24 - 12 oz bottles
Big
24 - 12 oz bottles
Big
12 - 75 cl bottles
Small
750 cc per bottle
Small
16 - 500 g tins
Big
24 - 12 oz bottles
Big
24 - 355 ml bottles
Big
24 - 0.5 l bottles
Big
500 ml
Small

,ProductID,ProductName,CategoryID,QuantityPerUnit,UnitPrice,UnitsInStock,ProductSize
0,1,Chai,1,10 boxes x 20 bags,18.00,39,Big
1,2,Chang,1,24 - 12 oz bottles,19.00,17,Big
23,24,Guaraná Fantástica,1,12 - 355 ml cans,4.50,20,Small
33,34,Sasquatch Ale,1,24 - 12 oz bottles,14.00,111,Big
34,35,Steeleye Stout,1,24 - 12 oz bottles,18.00,20,Big
37,38,Côte de Blaye,1,12 - 75 cl bottles,263.50,17,Small
38,39,Chartreuse verte,1,750 cc per bottle,18.00,69,Small
42,43,Ipoh Coffee,1,16 - 500 g tins,46.00,17,Big
66,67,Laughing Lumberjack Lager,1,24 - 12 oz bottles,14.00,52,Big
69,70,Outback Lager,1,24 - 355 ml bottles,15.00,15,Big
74,75,Rhönbräu Klosterbier,1,24 - 0.5 l bottles,7.75,125,Big
75,76,Lakkalikööri,1,500 ml,18.00,57,Small

<br></br>
<br></br>
## Exercise 6

### Use OpenAI API to create the COLUMN 'ProductSize' for `df`

with the <b><u>PARAMETERS</u></b> and the <b><u>CONTEXT</u></b> from above

<p style="font-size:20px;color:Tomato"> This time the Product should be categorize as "Big" or "Small" <u>  COMPARED  </u> to all other Products</p>

In [54]:
df = pd.read_csv("NORTHWND_prd.csv", encoding="cp1252")
df = df.loc[df.CategoryID == 1, ['ProductID', 'ProductName', 'CategoryID','QuantityPerUnit', 'UnitPrice', 'UnitsInStock']]
df["ProductSize"] = None
all_quantities = df["QuantityPerUnit"].tolist()

context_prompt = "You're helping me to categorize each product by its 'QuantityPerUnit' description , the categories are 'Big' or 'Small'."
for i in df.index:
  
  instructions_prompt = f"""
   Given the following QuantityPerUnit: {df.loc[i, "QuantityPerUnit"]}, and all products have these QuantityPerUnit values: {all_quantities}.
  Make your analysis and decide if the Product is big or small in comparison to all the other products and return a single word: Big or Small.
  """
  completion = client.chat.completions.create(
    model="gpt-4o",
    messages=[
      {"role": "system", "content":context_prompt},
      {"role": "user", "content": instructions_prompt}
    ],
    temperature=0.0,
    max_tokens=5
  )
  df.loc[i, "ProductSize"] = completion.choices[0].message.content
  
df

,ProductID,ProductName,CategoryID,QuantityPerUnit,UnitPrice,UnitsInStock,ProductSize
0,1,Chai,1,10 boxes x 20 bags,18.00,39,Big
1,2,Chang,1,24 - 12 oz bottles,19.00,17,Big
23,24,Guaraná Fantástica,1,12 - 355 ml cans,4.50,20,Small
33,34,Sasquatch Ale,1,24 - 12 oz bottles,14.00,111,Big
34,35,Steeleye Stout,1,24 - 12 oz bottles,18.00,20,Big
37,38,Côte de Blaye,1,12 - 75 cl bottles,263.50,17,Small
38,39,Chartreuse verte,1,750 cc per bottle,18.00,69,Small
42,43,Ipoh Coffee,1,16 - 500 g tins,46.00,17,Big
66,67,Laughing Lumberjack Lager,1,24 - 12 oz bottles,14.00,52,Big
69,70,Outback Lager,1,24 - 355 ml bottles,15.00,15,Small
74,75,Rhönbräu Klosterbier,1,24 - 0.5 l bottles,7.75,125,Big
75,76,Lakkalikööri,1,500 ml,18.00,57,Small